name: Docker

on:
  schedule:
    - cron: "45 3 * * *"
  push:
    branches: [ master ]

jobs:

  synctags:

    name: Sync Tags
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PA_TOKEN }}

      - name: Sync Tags
        run: |
          git remote add fork https://x-access-token:${PA_TOKEN}@github.com/genx7up/ramium.git
          for TAG in $(comm -23 <(git ls-remote --tags fork | grep -v '\^{}' | grep -v '-' | awk '{print $2}') <(git ls-remote --tags origin | grep -v '\^{}' | awk '{print $2}')); do
            git tag $TAG `git log master $TAG..master --ancestry-path --merges --oneline | tail -n1 | awk '{print $1;}'`
            #git fetch fork $TAG:$TAG --no-tags
            git push origin --tags
          done
          
