name: Docker

on:
  schedule:
    - cron: "45 3 * * *"
  push:
    branches: [ master ]

jobs:

  synctags:

    name: Sync Tags
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PA_TOKEN }}

      - name: Sync Tags
        run: |
          git remote add fork https://x-access-token:${PA_TOKEN}@github.com/genx7up/ramium.git
          for TAG in $(comm -23 <(git ls-remote --tags fork | grep -v '\^{}' | grep -v '-' | awk '{print $2}') <(git ls-remote --tags origin | grep -v '\^{}' | awk '{print $2}')); do
            echo $TAG
            git tag
            echo "fetch"
            git fetch --depth=1 fork $TAG:$TAG
            git tag
            echo "push"
            git push origin --tags
            echo "done"
          done
          
