name: Docker

on:
  push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Update
      run: |
        echo ${{ secrets.PA_TOKEN }}
        echo ${{ secrets.PA_TOKEN }}
